LoginFuzzy/Pages/HistorialPages/_Delete.cshtml.cs
using LoginFuzzy.Model;
using LoginFuzzy.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace LoginFuzzy.Pages.Shared
{
    [Authorize]
    public class _DeleteModel : PageModel
    {
        private readonly AuthDbContext _authDbContext;
        private readonly UserManager<ApplicationUser> futbolista;
        public _DeleteModel(UserManager<ApplicationUser> futbolista, AuthDbContext authDbContext)
        {
            _authDbContext = authDbContext;
            this.futbolista = futbolista;
        }

        [BindProperty]
        public Futbolista Futbolista { get; set; }

        public async Task<IActionResult> OnGetDeleteAsync(int id = 0)
        {
            if (id != 0)
            {
                Futbolista = await _authDbContext.Futbolista.FindAsync(id);
            }
            return Page();
        }
        public async Task<IActionResult> OnPostDeletingAsync()
        {
            if (ModelState.IsValid)
            {
                var futbolistafromDB = await _authDbContext.Futbolista.FindAsync(Futbolista.IdFutbolista);
                if(futbolistafromDB != null)
                {
                    _authDbContext.Remove(futbolistafromDB);
                    await _authDbContext.SaveChangesAsync();
                }
                return RedirectToPage("/Historial");
            }
            return RedirectToPage("/Historial");
        }
    }
}

LoginFuzzy/Pages/HistorialPages/_Lista.cshtml.cs
using LoginFuzzy.Model;
using LoginFuzzy.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace LoginFuzzy.Pages.Shared
{
    [Authorize]
    public class _ListaModel : PageModel
    {
        private readonly AuthDbContext _authDbContext;
        private readonly UserManager<ApplicationUser> futbolista;
        public _ListaModel(UserManager<ApplicationUser> futbolista, AuthDbContext authDbContext)
        {
            _authDbContext = authDbContext;
            this.futbolista = futbolista;
        }

        [BindProperty]
        public Futbolista Futbolista { get; set; }

        public async Task<IActionResult> OnGetListaAsync(int id = 0)
        {
            if (id != 0)
            {
                Futbolista = await _authDbContext.Futbolista.FindAsync(id);
            }
            return Page();
        }
    }
}

LoginFuzzy/Pages/HistorialPages/_PartialHistorial.cshtml.cs
using LoginFuzzy.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LoginFuzzy.Pages.Shared
{
    [Authorize]
    public class _PartialHistorialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

LoginFuzzy/Pages/HistorialPages/_Delete.cshtml
@page
@model LoginFuzzy.Pages.Shared._DeleteModel
@{
    Layout = null;
}
<div class="row">
    <form method="post" onsubmit="submitdelete()">
         <div class="col-md-12">
            <div class="centrado">
                <h5>¿Desea eliminar este jugador?</h5>
            </div>
            <p/>
            <div class="row justify-content-between">
                <div class="col-6">
                    <input type="hidden" asp-for="Futbolista.IdFutbolista"/>
                    <button onclick="closePopup()" type="submit" class="btn btn-danger border-dark col-12" asp-page-handler="Deleting">Sí</button>
                </div>
                <div class="col-6">
                    <button class="btn btn-light border-dark col-12" onclick="closePopup()" type="button">No</button>
                </div>
            </div>
        </div>   
    </form>
</div>

LoginFuzzy/Pages/HistorialPages/_Lista.cshtml
@page
@model LoginFuzzy.Pages.Shared._ListaModel
@{
    Layout = null;
}

<style>
    table,
    td,
    th {
      border-collapse: collapse;
    }
    
    th,
    td {
      padding: 5px;
      border: solid 1px;
      text-align: center;
    }
    
    .vtable td {
      background: lightgray;
    }

    .ressa {
        overflow: auto;
    }
</style>

<div class="container col-md-12 ressa">
    <form method="get">
        <table class = "vtable">
          <col>
          <col>
          <colgroup span="5"></colgroup>
          <thead>
          </thead>
          <tbody>
            <tr>
              <th colspan="2" rowspan="6" scope="rowgroup">Atributos Físicos</th>
              <th colspan="2" scope="row">Altura</th>
              <td>@Model.Futbolista.altura</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Peso</th>
              <td>@Model.Futbolista.peso</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Musculatura</th>
              <td>@Model.Futbolista.musculatura</td>
            </tr>
        		<tr>
              <th colspan="2" scope="row">Velocidad</th>
              <td>@Model.Futbolista.velocidad</td>
            </tr>
        		<tr>
              <th colspan="2" scope="row">Resistencia</th>
              <td>@Model.Futbolista.resistencia</td>
            </tr>
        		<tr>
              <th colspan="2" scope="row">Agilidad</th>
              <td>@Model.Futbolista.agilidad</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <th colspan="2" rowspan="2" scope="rowgroup" align="center">Atributos Mentales</th>
              <th colspan="2" scope="row">Confianza</th>
              <td>@Model.Futbolista.confianza</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Concentración</th>
              <td>@Model.Futbolista.concentracion</td>
            </tr>
          </tbody>
        	<tbody>
            <tr>
              <th colspan="2" rowspan="2" scope="rowgroup">Atributos Tácticos</th>
              <th colspan="2" scope="row">Toma de decisiones</th>
              <td>@Model.Futbolista.decisiones</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Creatividad</th>
              <td>@Model.Futbolista.creatividad</td>
            </tr>
          </tbody>
        	<tbody>
            <tr>
              <th colspan="2" rowspan="3" scope="rowgroup">Atributos Técnicos</th>
              <th colspan="2" scope="row">Dribling</th>
              <td>@Model.Futbolista.dribling</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Pases</th>
              <td>@Model.Futbolista.pases</td>
            </tr>
            <tr>
              <th colspan="2" scope="row">Finalización</th>
              <td>@Model.Futbolista.finalizacion</td>
            </tr>
          </tbody>
        	<tbody>
        		<tr>
        			<th colspan="5" scope="colgroup">Resultados</th>
        		</tr>
        		<tr>
              <th colspan="1" scope="col">Defensa Lateral</th>
        			<th colspan="1" scope="col">Defensa Central</th>
        			<th colspan="1" scope="col">Medio Campista</th>
        			<th colspan="1" scope="col">Delantero</th>
        			<th colspan="1" scope="col">Portero</th>
            </tr>
        		<tr>
        			<td>@Model.Futbolista.DL</td>
        			<td>@Model.Futbolista.DC</td>
        			<td>@Model.Futbolista.MC</td>
        			<td>@Model.Futbolista.FW</td>
        			<td>@Model.Futbolista.PT</td>
        		</tr>
        	</tbody>
        </table>
   </form>
</div>

LoginFuzzy/Pages/HistorialPages/_PartialHistorial.cshtml
@model List<LoginFuzzy.Model.Futbolista>

@{
    Layout = null;
}

<style>
    .baka {
        display: inline-block;
        width: 68px;
        font-size: 12px;
        margin: 2px;
    }

    .marginmin {
        margin: 2px;
    }

    .mensajto {
        position: relative;
        height: 60vh;
    }

    #baloncito {
        width: 250px;
        max-width: 100%;
        height: auto;
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    #baloncitopartner {   
         margin: 5px;
         width: 100%;
         position: absolute;
         top: 60%;
         left: 50%;
         transform: translate(-50%, -50%);
    }

    .margencartitas {
        width: 270px;
        margin: 0 -20px 15px 0;
    }

    .cartascentradas {
        display: flex;
        justify-content:center;
    }
</style>

@if (Model.Count() > 0)
{
    @foreach (var item in Model)
    {
        <div class="col cartascentradas">
            <div class="card margencartitas">
                <div class="card-body">
                    <h4 class="card-title">@item.nombre</h4>
                    <div class="row-3">
                        <label class="baka">DL: @item.DL</label>
                        <label class="baka">DC: @item.DC</label>
                        <label class="baka">MC: @item.MC</label>
                    </div>
                    <div class="row-2">
                        <label class="baka">FW: @item.FW</label>
                        <label class="baka">PT: @item.PT</label>
                    </div>
                    <div class="row-2">
                        <a id="eliminado" title="Eliminar" onclick="showInPopup('@Url.Page("/HistorialPages/_Delete", "Delete",new {id=item.IdFutbolista},Context.Request.Scheme)','Eliminación de Jugador')" class="btn btn-danger float-end marginmin"><i class="bi bi-trash"></i></a>
                        <a id="vistazo" title="Visualizar" onclick="showInPopup('@Url.Page("/HistorialPages/_Lista", "Lista",new {id=item.IdFutbolista},Context.Request.Scheme)','@item.nombre')" class="btn btn-primary float-end marginmin"><i class="bi bi-eye"></i></a>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="mensajto">
        <img id="baloncito" src="/images/NotFound.png"/>
        <br/>
        <h3 class="centrado" id="baloncitopartner">No se encontraron resultados.</h3>
    </div>
}