LoginFuzzy/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace LoginFuzzy.ViewModels
{
    public class Login
    {
        [Required(ErrorMessage ="Debe ingresar un nombre de usuario.")]
        public string? Username { get; set; }
        [Required(ErrorMessage = "Debe ingresar una contraseña.")]
        [DataType(DataType.Password)]
        public string? Password { get; set; }
        public bool RememberMe { get; set; }    
    }
}

LoginFuzzy/ViewModels/Registro.cs
using System.ComponentModel.DataAnnotations;

namespace LoginFuzzy.ViewModels
{
    public class Registro
    {
        [Required(ErrorMessage ="Debe ingresar un nombre de usuario.")]
        public string? Username { get; set; }

        [Required(ErrorMessage = "Debe ingresar un correo electrónico.")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^((([!#$%&'*+\-/=?^_`{|}~\w])|([!#$%&'*+\-/=?^_`{|}~\w][!#$%&'*+\-/=?^_`{|}~\.\w]{0,}[!#$%&'*+\-/=?^_`{|}~\w]))[@]\w+([-.]\w+)*\.\w+([-.]\w+)*)$", ErrorMessage ="Ingrese un correo electrónico válido.")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Debe ingresar una contraseña.")]
        [DataType(DataType.Password)]
        public string? Password { get; set; }

        [Required(ErrorMessage = "Debe ingresar la confirmación de la contraseña.")]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage ="Las contraseñas no coinciden.")]
        public string? ConfirmPassword { get; set; }
    }
}

LoginFuzzy/Pages/Index.cshtml.cs
using LoginFuzzy.Model;
using LoginFuzzy.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace LoginFuzzy.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly UserManager<ApplicationUser> futbolista;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;

        public IndexModel(ILogger<IndexModel> logger, UserManager<ApplicationUser> futbolista, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            this.futbolista = futbolista;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }
       
        public void OnGet()
        {
            ViewData["UsuarioNombre"] = futbolista.GetUserName(User);
        }

        public PartialViewResult OnGetLoginA()
        {
            ModelState.Clear();
            return new PartialViewResult
            {
                ViewName = "AuthenticationPages/_Login",
                ViewData = new ViewDataDictionary<Login>(ViewData, new Login { })
            };
        }

        public async Task<IActionResult> OnPostLoginAAsync(Login ModelLog, string? returnUrl = null)
        {
            var errores = ModelState.Values.SelectMany(x => x.Errors);
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(ModelLog.Username, ModelLog.Password, ModelLog.RememberMe, false);
                if (identityResult.Succeeded)
                {
                    if (returnUrl == null || returnUrl == "/")
                    {
                        TempData["success"] = "Ingresado Correctamente.";
                        //return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Nombre de Usuario o Contraseña Incorrecta.");
                }
            }
            return new PartialViewResult
            {
                ViewName = "AuthenticationPages/_Login",
                ViewData = new ViewDataDictionary<Login>(ViewData, ModelLog)
            };
        }

        public PartialViewResult OnGetRegistroR()
        {
            ModelState.Clear();
            return new PartialViewResult
            {
                ViewName = "AuthenticationPages/_Registro",
                ViewData = new ViewDataDictionary<Registro>(ViewData, new Registro { })
            };
        }

        public async Task<ActionResult> OnPostRegistroRAsync(Registro ModelReg)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser()
                {
                    UserName = ModelReg.Username,
                    Email = ModelReg.Email
                };
                IdentityResult result = await userManager.CreateAsync(user, ModelReg.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    //return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return new PartialViewResult
            {
                ViewName = "AuthenticationPages/_Registro",
                ViewData = new ViewDataDictionary<Registro>(ViewData, ModelReg)
            };
        }

    }
}

LoginFuzzy/Pages/AuthenticationPages/_Login.cshtml
@model LoginFuzzy.ViewModels.Login
@{
    Layout = null;
}

<style>
    .passwordvis {
        display: inline!important;
    }
    .passderecha {
        display: initial;
        padding: 10px 10px 3px 3px;
        margin-left: -40px;
        opacity: 0.7;
    }
    .passderechaP2 {
        font-size: 18px;
    }
</style>

<script>
    var contador = 0;
    /*function showText (x) {
        x.type = "text";
        document.getElementById("togglePassword").classList.toggle("bi-eye-slash-fill");
        document.getElementById("togglePassword").classList.toggle("bi-eye-fill");
        contador = 1;
    }*/

    $('#togglePassword').on('touchstart mousedown', function(e){
        document.getElementById("passwordvalue").type = "text";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contador = 1;
        e.preventDefault();
    });

    /*function showPassword (x) {
        x.type = "password";
        document.getElementById("togglePassword").classList.toggle("bi-eye-slash-fill");
        document.getElementById("togglePassword").classList.toggle("bi-eye-fill");
        contador = 0;
    }*/

    $('#togglePassword').on('touchend mouseup', function(e){
        document.getElementById("passwordvalue").type = "password";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contador = 0;
        e.preventDefault();
    });


    $('#togglePassword').on('touchcancel mouseout', function(e){
        if(contador == 1){
            document.getElementById("passwordvalue").type = "password";
            e.classList.toggle("bi-eye-slash-fill");
            e.classList.toggle("bi-eye-fill");
            contador = 0;
            e.preventDefault();
        }
    });

    /*function showPasswordHover (x) {
        if(contador == 1){
            x.type = "password";
            document.getElementById("togglePassword").classList.toggle("bi-eye-slash-fill");
            document.getElementById("togglePassword").classList.toggle("bi-eye-fill");
            contador = 0;
        }
    }*/

</script>

<div class="modal fade" tabindex="-1" id="form-modallog" role="dialog" aria-hidden="true" aria-labelledby="loginLabel">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginLabel">Login</h5>
        <button id="videomodalexample" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="row justify-content-center align-items-center">
                <div class="col-sm-12 col-md-12">
                    <form asp-page-handler="LoginA">
                        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()"/>
                        <div asp-validation-summary="ModelOnly" class="text-danger">
                        </div>
                         <div class="mb-3">
                            <label class="form-label" asp-for="Username">Usuario</label>
                            <input type="text" asp-for="Username" class="form-control" id="inputnombrelog"/>
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" asp-for="Password">Contraseña</label>
                            <input type="password" asp-for="Password" class="form-control passwordvis" id="passwordvalue"/>
                            <a class="btn passderecha"><i class="passderechaP2 bi bi-eye-slash-fill" id="togglePassword"></i></a>
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" asp-for="RememberMe" class="form-check-input" id="recuerdame"/>
                            <label class="form-check-label" asp-for="RememberMe">¿Recordarme?</label>
                        </div>
                        <div class="mb-2">
                            <button id="butonlogin" type="button" class="btn btn-primary col-12 loadingclase" data-login="modal">Ingresar</button>
                        </div>
                        <div class="centrado">
                            <a class="cursorpunta" data-transport="ajax-register">¿Aún no estás registrado? Regístrate aquí.</a>
                        </div>
                    </form>
                </div>
            </div>
      </div>
    </div>
  </div>
</div>

LoginFuzzy/Pages/AuthenticationPages/_Registro.cshtml
@model LoginFuzzy.ViewModels.Registro
@{
    Layout = null;
}

<style>
    .passwordvisreg {
        display: inline!important;
    }
    .passderechare {
        display: initial;
        padding: 10px 10px 3px 3px;
        margin-left: -40px;
        opacity: 0.7;
    }
    .passderechaP2 {
        font-size: 18px;
    }
</style>

<script>
    var contador = 0;
    var contadito = 0;
    /*function showText (x) {
        x.type = "text";
        document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-slash-fill");
        document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-fill");
        contador = 1;
    }

    function showPassword (x) {
        x.type = "password";
        document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-slash-fill");
        document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-fill");
        contador = 0;
    }

    function showPasswordHover (x) {
        if(contador == 1){
            x.type = "password";
            document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-slash-fill");
            document.getElementById("togglePasswordRegistro").classList.toggle("bi-eye-fill");
            contador = 0;
        }
    }*/

    $('#togglePasswordRegistro').on('touchstart mousedown', function(e){
        document.getElementById("passwordregistro").type = "text";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contador = 1;
        e.preventDefault();
    });


    $('#togglePasswordRegistro').on('touchend mouseup', function(e){
        document.getElementById("passwordregistro").type = "password";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contador = 0;
        e.preventDefault();
    });


    $('#togglePasswordRegistro').on('touchcancel mouseout', function(e){
        if(contador == 1){
            document.getElementById("passwordregistro").type = "password";
            e.classList.toggle("bi-eye-slash-fill");
            e.classList.toggle("bi-eye-fill");
            contador = 0;
            e.preventDefault();
        }
    });

    /*function showTextPart2 (x) {
        x.type = "text";
        document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-slash-fill");
        document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-fill");
        contadito = 1;
    }

    function showPasswordPart2 (x) {
        x.type = "password";
        document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-slash-fill");
        document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-fill");
        contadito = 0;
    }

    function showPasswordHoverPart2 (x) {
        if(contadito == 1){
            x.type = "password";
            document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-slash-fill");
            document.getElementById("toggleConfirmPassword").classList.toggle("bi-eye-fill");
            contadito = 0;
        }
    }*/

    $('#toggleConfirmPassword').on('touchstart mousedown', function(e){
        document.getElementById("passwordconfirmarregistro").type = "text";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contadito = 1;
        e.preventDefault();
    });


    $('#toggleConfirmPassword').on('touchend mouseup', function(e){
        document.getElementById("passwordconfirmarregistro").type = "password";
        e.classList.toggle("bi-eye-slash-fill");
        e.classList.toggle("bi-eye-fill");
        contadito = 0;
        e.preventDefault();
    });


    $('#toggleConfirmPassword').on('touchcancel mouseout', function(e){
        if(contadito == 1){
            document.getElementById("passwordconfirmarregistro").type = "password";
            e.classList.toggle("bi-eye-slash-fill");
            e.classList.toggle("bi-eye-fill");
            contadito = 0;
            e.preventDefault();
        }
    });
</script>


<div class="modal fade" tabindex="-1" id="form-modalreg" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Registro</h5>
        <button id="videomodalexample" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <div class="row justify-content-center align-items-center">
                <div class="col-sm-12 col-md-12">
                    <form asp-page-handler="RegistroR" onsubmit="butonregistro.disabled = true; return true;">
                        <input name="IsValidP2" type="hidden" value="@ViewData.ModelState.IsValid.ToString()"/>
                        <div asp-validation-summary="ModelOnly" class="text-danger">
                        </div>
                         <div class="mb-3">
                            <label class="form-label" asp-for="Username">Usuario</label>
                            <input type="text" asp-for="Username" class="form-control" id="inputuserreg"/>
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" asp-for="Email">E-mail</label>
                            <input type="text" asp-for="Email" class="form-control" id="inputemail"/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="row mb-3">
                            <div class="col-md-6 emer">
                                <label class="form-label" asp-for="Password">Contraseña</label>
                                <input type="password" asp-for="Password" class="form-control passwordvisreg" id="passwordregistro"/>
                                <a class="btn passderechare"><i class="passderechaP2 bi bi-eye-slash-fill" id="togglePasswordRegistro"></i></a>
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label" asp-for="ConfirmPassword">Confirmar Contraseña</label>
                                <input type="password" asp-for="ConfirmPassword" class="form-control passwordvisreg" id="passwordconfirmarregistro"/>
                                <a class="btn passderechare"><i class="passderechaP2 bi bi-eye-slash-fill" id="toggleConfirmPassword"></i></a>
                                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-2">
                            <button id="butonregistro" type="button" class="btn btn-primary col-12 loadingclase" data-registro="modalP2">Registrarse</button>
                        </div>
                        <div class="centrado">
                            <a class="cursorpunta" data-teleport="ajax-login">¿Ya estás registrado? Ingresa aquí.</a>
                        </div>
                    </form>
                </div>
            </div>
      </div>
    </div>
  </div>
</div>